export default (i18n) => {
  const title = document.querySelector('#title')
  const subtitle = document.querySelector('#subtitle')
  const urlLabel = document.querySelector('#url-label')
  const addButton = document.querySelector('#add-button')
  const settingsBtn = document.querySelector('#settingsBtn')
  const selectRussian = document.querySelector('[data-lang="ru"]')
  const selectEnglish = document.querySelector('[data-lang="en"]')
  const setInterval = document.querySelector('#setInterval')
  const postCloseBtn = document.querySelector('#postCloseBtn')
  const readButton = document.querySelector('#readButton')
  const updateIntervalLabel = document.querySelector('#updateIntervalLabel')
  const settingsFormLabel = document.querySelector('#settingsFormLabel')
  const settingsCloseBtn = document.querySelector('#settingsCloseBtn')
  const settingsSaveBtn = document.querySelector('#settingsSaveBtn')

  title.textContent = i18n.t('elements.title')
  subtitle.textContent = i18n.t('elements.subtitle')
  urlLabel.textContent = i18n.t('elements.placeholder')
  addButton.textContent = i18n.t('elements.button')
  settingsBtn.textContent = i18n.t('settings.settingsBtn')
  selectRussian.textContent = i18n.t('settings.langRu')
  selectEnglish.textContent = i18n.t('settings.langEn')
  setInterval.textContent = i18n.t('settings.setInterval')
  postCloseBtn.textContent = i18n.t('postModal.closePost')
  readButton.textContent = i18n.t('postModal.readPost')
  updateIntervalLabel.textContent = i18n.t('settingsModal.modalTitle')
  settingsFormLabel.textContent = i18n.t('settingsModal.modalSubTitle')
  settingsCloseBtn.textContent = i18n.t('settingsModal.closeButton')
  settingsSaveBtn.textContent = i18n.t('settingsModal.saveButton')
}
